apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: honya

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: honya-secrets
    envs:
      - secrets.env
