CREATE TABLE catalog.categories (
    id UUID PRIMARY KEY,
    slug VARCHAR(255),
    name VARCHAR(255),
    description VARCHAR(255)
);

CREATE TABLE catalog.books (
    id UUID PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(255),
    author VARCHAR(255),
    price INTEGER,
    pages_count INTEGER,
    year_published INTEGER,
    publisher VARCHAR(255),
    weight REAL,
    stock_quantity INTEGER,
    purchase_count INTEGER,
    rating REAL
);

CREATE TABLE catalog.media (
    id UUID PRIMARY KEY,
    url VARCHAR(255),
    alt_text VARCHAR(255)
);

CREATE TABLE catalog.book_categories (
    book_id UUID NOT NULL,
    category_id UUID NOT NULL,
    PRIMARY KEY (book_id, category_id),
    CONSTRAINT fk_book_categories_book FOREIGN KEY (book_id) REFERENCES catalog.books(id),
    CONSTRAINT fk_book_categories_category FOREIGN KEY (category_id) REFERENCES catalog.categories(id)
);

CREATE TABLE catalog.book_media (
    id UUID PRIMARY KEY,
    book_id UUID,
    media_id UUID,
    is_cover BOOLEAN,
    media_order INTEGER,
    CONSTRAINT fk_book_media_book FOREIGN KEY (book_id) REFERENCES catalog.books(id),
    CONSTRAINT fk_book_media_media FOREIGN KEY (media_id) REFERENCES catalog.media(id)
);

CREATE TABLE catalog.catalog_processed_order_events (
    id UUID PRIMARY KEY,
    order_id UUID NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_catalog_processed_order_events_order_id UNIQUE (order_id)
);

CREATE TABLE cart.carts (
    id UUID PRIMARY KEY,
    updated_at TIMESTAMP WITH TIME ZONE,
    user_id UUID
);

CREATE TABLE cart.cart_items (
    id UUID PRIMARY KEY,
    cart_id UUID,
    book_id UUID,
    quantity INTEGER,
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES cart.carts(id)
);

CREATE TABLE cart.cart_processed_order_events (
    id UUID PRIMARY KEY,
    order_id UUID NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_cart_processed_order_events_order_id UNIQUE (order_id)
);

CREATE TABLE "order".orders (
    id UUID PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    address VARCHAR(255),
    city VARCHAR(255),
    provider VARCHAR(255),
    status VARCHAR(255),
    is_paid BOOLEAN,
    total_amount INTEGER,
    user_id UUID
);

CREATE TABLE "order".order_items (
    id UUID PRIMARY KEY,
    order_id UUID,
    book_id UUID,
    quantity INTEGER,
    price INTEGER,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES "order".orders(id)
);

CREATE TABLE "order".order_outbox_messages (
    id UUID PRIMARY KEY,
    event_type VARCHAR(255),
    aggregate_id UUID,
    payload TEXT,
    status VARCHAR(255),
    attempts INTEGER NOT NULL,
    next_attempt_at TIMESTAMP WITH TIME ZONE,
    sent_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_order_outbox_due
    ON "order".order_outbox_messages (status, next_attempt_at, created_at);

CREATE TABLE review.reviews (
    id UUID PRIMARY KEY,
    rating INTEGER,
    vote_count INTEGER,
    content VARCHAR(255),
    user_id UUID,
    book_id UUID
);

CREATE TABLE review.review_votes (
    id UUID PRIMARY KEY,
    is_up BOOLEAN,
    user_id UUID,
    review_id UUID
);

CREATE TABLE discount.discounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    start_date DATE,
    end_date DATE,
    type VARCHAR(255),
    value DOUBLE PRECISION,
    category VARCHAR(255),
    operator VARCHAR(255)
);

CREATE TABLE discount.discount_condition_value (
    discount_id INTEGER NOT NULL,
    condition_value VARCHAR(255),
    CONSTRAINT fk_discount_condition_value_discount FOREIGN KEY (discount_id) REFERENCES discount.discounts(id)
);

CREATE TABLE article.articles (
    id UUID PRIMARY KEY,
    slug VARCHAR(255),
    title VARCHAR(255),
    content TEXT,
    author_id UUID,
    media_id UUID
);

CREATE TABLE article.article_tags (
    article_id UUID NOT NULL,
    tags VARCHAR(255),
    CONSTRAINT fk_article_tags_article FOREIGN KEY (article_id) REFERENCES article.articles(id)
);

CREATE TABLE ticket.tickets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255),
    title VARCHAR(255),
    description TEXT,
    status VARCHAR(255),
    response TEXT,
    created_at TIMESTAMP WITH TIME ZONE,
    responded_at TIMESTAMP WITH TIME ZONE,
    placed_by_id UUID,
    respondent_id UUID
);

CREATE TABLE "user".users (
    id VARCHAR(255) PRIMARY KEY
);
